# Generated by Django 6.0.2 on 2026-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trial_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('EXPIRED', 'Expired')], default='FREE_TRIAL', max_length=20),
        ),
    ]
