# Generated by Django 6.0.2 on 2026-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Student profile photo', null=True, upload_to='student_photos/'),
        ),
    ]
