# Generated by Django 6.0.2 on 2026-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_profile_photo'),
        ('organizations', '0002_organization_trial_end_organization_trial_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('email', 'organization'), ('roll_number', 'organization')},
        ),
    ]
