# Generated by Django 6.0.2 on 2026-02-11 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.DateField(default=datetime.date(2026, 2, 11)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('student', 'date')},
        ),
    ]
