# Generated by Django 6.0.2 on 2026-02-12 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('teachers', '0002_alter_teacherdepartment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdepartment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
            preserve_default=False,
        ),
    ]
