# Generated by Django 6.0.2 on 2026-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacherdepartment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdepartment',
            name='subject',
            field=models.CharField(default='guest', max_length=100),
        ),
    ]
