# Generated by Django 6.0.2 on 2026-02-12 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('teachers', '0004_teacherdepartment_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherDepartment',
            new_name='Teachers',
        ),
    ]
